global using MediatR;
global using Mapster;
global using Keepass.Application.Extensions;
global using Keepass.Infrastructure.Extensions;
global using Keepass.Wpf.Contracts;
global using Keepass.Wpf.Models;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Windows;
